// <auto-generated/>

namespace Microsoft.Teams.Apps.FAQPlusPlus.Configuration
{
    /// <summary>
    /// Mvc Application
    /// </summary>
    public class MvcApplication : System.Web.HttpApplication
    {
    }
}