export interface TicketEntity {
    TicketId: string,
    Status: number,
    Title: string,
    Description: string,
    DateCreated: Date,
    RequesterName: string,
    RequesterUserPrincipalName: string,
    RequesterGivenName: string,
    RequesterConversationId: string,
    SmeCardActivityId: string,
    SmeThreadConversationId: string,
    DateAssigned?: string,
    AssignedToName?: string,
    AssignedToObjectId?: string,
    DateClosed?: string,
    LastModifiedByName: string,
    LastModifiedByObjectId: string,
    UserQuestion: string,
    KnowledgeBaseAnswer: string,
    Timestamp?: string,
}